spring.application.name=gateway
server.port=8080
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
#logging.level.org.springframework=TRACE
# Routes

# 1\uFE0F\u20E3 User-service (login/register) \u2192 No JWT required
spring.cloud.gateway.server.webflux.routes[0].id=user-service-auth
spring.cloud.gateway.server.webflux.routes[0].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/auth/**

# 2\uFE0F\u20E3 User-service (other endpoints like /users) \u2192 JWT required
spring.cloud.gateway.server.webflux.routes[1].id=user-service-secure
spring.cloud.gateway.server.webflux.routes[1].uri=lb://user-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/users/**
spring.cloud.gateway.server.webflux.routes[1].filters[0]=JwtAuthenticationFilter

# 3\uFE0F\u20E3 Product-service (secured)
spring.cloud.gateway.server.webflux.routes[2].id=product-service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/products/**
spring.cloud.gateway.server.webflux.routes[2].filters[0]=JwtAuthenticationFilter

# 4\uFE0F\u20E3 Order-service (secured)
spring.cloud.gateway.server.webflux.routes[3].id=order-service
spring.cloud.gateway.server.webflux.routes[3].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/orders/**
spring.cloud.gateway.server.webflux.routes[3].filters[0]=JwtAuthenticationFilter


# Enable Micrometer tracing
management.tracing.sampling.probability=1.0   
# 100% tracing, reduce to 0.1 in prod

# Zipkin endpoint (make sure Zipkin is running on 9411)
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

# Show traceId & spanId in logs for correlation
logging.pattern.level=%5p [${spring.application.name:},traceId=%X{traceId:-},spanId=%X{spanId:-}]